export const BACKGROUNDS = [
  "Acolyte",
  "Charlatan",
  "Criminal",
  "Entertainer",
  "Folk Hero",
  "Guild Artisan",
  "Hermit",
  "Noble",
  "Outlander",
  "Sage",
  "Sailor",
  "Soldier",
  "Urchin",
  "City Watch",
  "Clan Crafter",
  "Cloistered Scholar",
  "Courtier",
  "Faction Agent",
  "Far Traveler",
  "Inheritor",
  "Knight of the Order",
  "Mercenary Veteran",
  "Haunted One",
  "Investigator",
  "Anthropologist",
  "Archaeologist",
  "Custom",
] as const;

export type Background = (typeof BACKGROUNDS)[number];
